#! /bin/bash

#TODO: File based config
#      With parsing

printf "
     ___      ________    _____                __       
 __ / / | /| / /_  __/   / ___/______ __    __/ /__ ____
/ // /| |/ |/ / / /     / /__/ __/ _ \`/ |/|/ / / -_) __/
\___/ |__/|__/ /_/______\___/_/  \_,_/|__,__/_/\__/_/   
   ____                                        
  / __/__ ___  ____(_)___                               
 / _// -_) _ \/ __/ / __/                               
/_/  \__/_//_/_/ /_/_/                                  
\n\n\n"
printf "[*]     JWT_Crawler\n"
printf "[*]     Fenrir\n\n"
printf "Enter URL:\n> "
#TODO: add http:// if not detected
read URL
printf "Enter TOKEN generator location:\n> "
#TODO: add leading / if not detected
#TODO: ask for data
read tok_gen_location

printf "Enter username:\n> "
read username
printf "Enter password:\n> "
read password

printf "Trying to get token from: $URL$tok_gen_location with data: {\"username\":\"$username\",\"password\":\"$password\"}"
TOKEN=$(curl -s -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' --data '{"username":$username,"password":$password}' $URL$tok_gen_location | jq -r)
printf "\nToken should be "$TOKEN"\n"

#TODO: check file has been created, is readable and empty. If not empty,
#Ask to continue
printf "Enter output file location:\n> "
read outputFile

printf "Enter wordlist location:\n> "
read wordlist

printf "Target URL is "$URL > $outputFile
#TODO: Recursive mode?
for word in `cat "$wordlist"`
do
    printf "\nGetting $word" >> "$outputFile"
    printf "\nGetting $word"
    curl -H 'Accept: application/json' -H "Authorization: Bearer ${TOKEN}" $URL$word >> $outputFile
done

printf "\nResult is in file $outputFile\n"
